name: deploy-prd

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "build.gradle"
      - "settings.gradle"
      - "Dockerfile.prd"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      branch: prd
      branch_upper: PRD
      tag_prefix: v-prd-
      dockerfile: Dockerfile.prd
      instance_env: prd
    secrets:
      ENV_CONTENT: ${{ secrets.ENV_CONTENT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TK_GITHUB_ACCESS_TOKEN: ${{ secrets.TK_GITHUB_ACCESS_TOKEN }}
      TK_GITHUB_ACCESS_TOKEN_OWNER: ${{ secrets.TK_GITHUB_ACCESS_TOKEN_OWNER }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      NETWORK_NAME: ${{ secrets.NETWORK_NAME }}